language: python

# versions to test against
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: "tarbell generate /tmp/throwaway"

